on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: "10.0.0"

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "pnpm"

      - run: pnpm install

      - run: pnpm -w build

      - run: pnpx pkg-pr-new publish './packages/*' './packages/@xframework/*'
